opt-commands: add uwurandom
getchoo/teawieBot pull request #112
Opened 2023-12-20 11:59 UTC by vgskye

mrowmewmeowrmewmrowmrowmrowmeowrmraowrmrowrnyaamraownyaaameowrmeowmraowmrowmrrmeowmeowrnyanyanya >///< *nuzzles* ;a;ahjhdfhkfghal;ahjgaurgafkfgaldsdhfjfgagaha :3 AAAAAAAAAAAAAAAA mrowrmeowrnyanyaaaaamrowmrwmreowmrrppurrrrmeowmraowmrowrmraowmrowmewmewnyaaaaamrownyanyaamrowmeowrnya

2023-12-20 12:14 UTC, hyperventilation commented
i approve

2023-12-21 03:00 UTC, 8ballpizza commented
need

2023-12-21 03:11 UTC, getchoo requested changes

2023-12-21 03:11 UTC, getchoo commented on src/commands/optional/uwurandom.rs
> +	length: u16,
maybe this could be an optional argument and we send a (sensible) random amount of uwurandom by default? (peak randomness)

2023-12-21 03:11 UTC, getchoo commented on src/commands/optional/uwurandom.rs
> +/// generate some amount of uwurandom
```suggestion
/// Generate some amount of uwurandom
```

nit

2023-12-21 03:11 UTC, getchoo commented on src/commands/optional/uwurandom.rs
> +	#[description = "the amount of uwurandom to generate"]
```suggestion
	#[description = "The amount of uwurandom to generate"]
```
ditto

2023-12-28 09:12 UTC, merged